{
  "formatVersion": "1.1",
  "component": {
    "group": "yoyosource",
    "module": "YAPION",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "ayeb7fwstfgsbn72elzqpys5ae"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "YAPION-0.8.0.jar",
          "url": "YAPION-0.8.0.jar",
          "size": 138091,
          "sha512": "8d711332f3782cb485f80f1dfac921f6d46892bc46d2c2169e82b4b145890751076782554b657dbcb9a0a91049a6e50410f257100047cbb88b3d77fbbeb03379",
          "sha256": "4c36ee4caae29c0d622b2f9c4d2175d0f5837fbd87de33dc04bc8cc7525c4878",
          "sha1": "349b48e8388b74eeb7161e84bdd23abe6ffad2e0",
          "md5": "786828060f23b785a569d3df8193666b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.objenesis",
          "module": "objenesis",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.0-alpha1"
          }
        }
      ],
      "files": [
        {
          "name": "YAPION-0.8.0.jar",
          "url": "YAPION-0.8.0.jar",
          "size": 138091,
          "sha512": "8d711332f3782cb485f80f1dfac921f6d46892bc46d2c2169e82b4b145890751076782554b657dbcb9a0a91049a6e50410f257100047cbb88b3d77fbbeb03379",
          "sha256": "4c36ee4caae29c0d622b2f9c4d2175d0f5837fbd87de33dc04bc8cc7525c4878",
          "sha1": "349b48e8388b74eeb7161e84bdd23abe6ffad2e0",
          "md5": "786828060f23b785a569d3df8193666b"
        }
      ]
    }
  ]
}
